name: "Setup Nix"
description: "Installs Nix with Elara and Tek Cachix configurations"
inputs:
  github-token:
    description: "GitHub Token for Nix access-tokens"
    required: true
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - uses: DeterminateSystems/nix-installer-action@v21
      with:
        extra-conf: |
          access-tokens = github.com=${{ inputs.github-token }}
          extra-substituters = https://elara.cachix.org https://tek.cachix.org
          extra-trusted-public-keys = elara.cachix.org-1:d129AMaRCJ6Q86oVUvIccZ1NsRZ6kyL5IkceevfQDWI= tek.cachix.org-1:+sdc73WFq8aEKnrVv5j/kuhmnW2hQJuqdPJF5SnaCBk=

    - uses: cachix/cachix-action@v16
      with:
        name: elara
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
