{-# LANGUAGE DuplicateRecordFields #-}

-- | High level representation of a class file.
module H2JVM.ClassFile (ClassFile (..), ClassFileAttribute (..), InnerClassInfo (..)) where

import Data.Data
import Data.Text (Text)
import Prettyprinter (encloseSep, line, parens)

import H2JVM.ClassFile.AccessFlags (ClassAccessFlag)
import H2JVM.ClassFile.Field (ClassFileField)
import H2JVM.ClassFile.Method (ClassFileMethod)
import H2JVM.ConstantPool (BootstrapMethod)
import H2JVM.Data.TypeMergingList (DataMergeable (merge), TypeMergingList, errorDifferentConstructors, toList)
import H2JVM.Internal.Pretty
import H2JVM.JVMVersion (JVMVersion)
import H2JVM.Name

-- | High-level representation of a Java class file.
data ClassFile = ClassFile
    { name :: QualifiedClassName
    -- ^ The fully qualified name of the class.
    , version :: JVMVersion
    -- ^ The target JVM/Java version
    , accessFlags :: [ClassAccessFlag]
    -- ^ Access flags and modifiers of the class (e.g. @public@, @abstract@).
    , superClass :: Maybe QualifiedClassName
    -- ^ The fully qualified name of the superclass (or 'Nothing' for @java/lang/Object@).
    , interfaces :: [QualifiedClassName]
    -- ^ The fully qualified names of the interfaces implemented by this class.
    , fields :: [ClassFileField]
    -- ^ Fields defined in the class.
    , methods :: [ClassFileMethod]
    -- ^ Methods defined in the class.
    , attributes :: TypeMergingList ClassFileAttribute
    -- ^ Additional class file attributes.
    }
    deriving (Show)

-- | Attributes that can be attached to a class file.
data ClassFileAttribute
    = -- | The @InnerClasses@ attribute, specifying the nested/inner class info.
      InnerClasses [InnerClassInfo]
    | -- | The @EnclosingMethod@ attribute.
      EnclosingMethod
    | -- | The @Synthetic@ attribute indicating this class was generated by the compiler.
      Synthetic
    | -- | The @Signature@ attribute for generic type information.
      Signature
    | -- | The name of the source file this class was compiled from.
      SourceFile Text
    | -- | The @SourceDebugExtension@ attribute.
      SourceDebugExtension
    | -- | The @Deprecated@ attribute indicating this class is deprecated.
      Deprecated
    | -- | The annotations visible at runtime.
      RuntimeVisibleAnnotations
    | -- | The annotations invisible at runtime.
      RuntimeInvisibleAnnotations
    | -- | Bootstrap methods for @invokedynamic@ instructions.
      BootstrapMethods [BootstrapMethod]
    deriving (Data, Eq, Show)

instance DataMergeable ClassFileAttribute where
    merge (InnerClasses a) (InnerClasses b) = InnerClasses (a <> b)
    merge EnclosingMethod EnclosingMethod = EnclosingMethod
    merge Synthetic Synthetic = Synthetic
    merge Signature Signature = Signature
    merge (SourceFile a) (SourceFile b) = SourceFile (a <> b)
    merge SourceDebugExtension SourceDebugExtension = SourceDebugExtension
    merge Deprecated Deprecated = Deprecated
    merge RuntimeVisibleAnnotations RuntimeVisibleAnnotations = RuntimeVisibleAnnotations
    merge RuntimeInvisibleAnnotations RuntimeInvisibleAnnotations = RuntimeInvisibleAnnotations
    merge (BootstrapMethods a) (BootstrapMethods b) = BootstrapMethods (a <> b)
    merge a b = errorDifferentConstructors a b

-- | Information about an inner class.
data InnerClassInfo = InnerClassInfo
    { innerClassInfo :: QualifiedClassName
    -- ^ The inner class being defined.
    , outerClassInfo :: QualifiedClassName
    -- ^ The enclosing outer class.
    , innerName :: Text
    -- ^ Simple name of the inner class.
    , accessFlags :: [ClassAccessFlag]
    -- ^ Access flags of the inner class.
    }
    deriving (Data, Eq, Show)

instance Pretty ClassFile where
    pretty ClassFile{name, version, accessFlags, superClass, interfaces, fields, methods, attributes} =
        hsep (pretty <$> accessFlags)
            <+> "class"
            <+> pretty name
            <+> parens (pretty version)
            <+> maybe "" (("extends" <+>) . pretty) superClass
            <+> (if null interfaces then "" else "implements" <+> pretty interfaces)
            <+> body
      where
        body = encloseSep open close sep (map pretty fields ++ map pretty methods ++ map pretty (toList attributes))
        open = "{"
        close = "}"
        sep = line

instance Pretty ClassFileAttribute where
    pretty (InnerClasses xs) = "InnerClasses" <+> pretty xs
    pretty EnclosingMethod = "EnclosingMethod"
    pretty Synthetic = "Synthetic"
    pretty Signature = "Signature"
    pretty (SourceFile x) = "SourceFile" <+> pretty x
    pretty SourceDebugExtension = "SourceDebugExtension"
    pretty Deprecated = "Deprecated"
    pretty RuntimeVisibleAnnotations = "RuntimeVisibleAnnotations"
    pretty RuntimeInvisibleAnnotations = "RuntimeInvisibleAnnotations"
    pretty (BootstrapMethods xs) = "BootstrapMethods" <+> pretty xs

instance Pretty InnerClassInfo where
    pretty InnerClassInfo{innerClassInfo, outerClassInfo, innerName, accessFlags} =
        pretty accessFlags <+> "inner class" <+> pretty innerClassInfo <+> "in" <+> pretty outerClassInfo <+> "named" <+> pretty innerName
